version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        sudo sed -i 's/xenial/bionic/g' /etc/apt/sources.list
        sudo apt update ;
        cat /etc/apt/sources.list
        sudo apt update && sudo apt install -y openssh-* ;
        sudo apt install -y build-*;
        sudo apt install -y  make ;
        sudo apt install -y flex bison bc ;
        sudo DEBIAN_FRONTEND=noninteractive apt -y install expect ;
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        if ! [ -d .git ]; then
          git clone --depth=1 $CIRCLE_REPOSITORY_URL .;
        fi
        if [[ $CIRCLE_BRANCH == pull/* ]]; then
           git fetch --depth=1 origin $CIRCLE_BRANCH/head;
        else
           git fetch --depth=1 origin $CIRCLE_BRANCH;
        fi
        git reset --hard $CIRCLE_SHA1
        sudo chmod 777 ~/project/ndk-auto-install ;
        ~/project/ndk-auto-install;
  - save_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
      paths:
        - ~/project/.git
  - run:
      name: clean
      command: |
        make mrproper
        cd tools/lkl && make clean-conf
        rm -rf ~/junit
  - run: mkdir -p ~//.ccache
  - restore_cache:
      key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}
  - run:
      name: build DPDK
      command: |
        if [ "$MKARG" = "dpdk=yes" ]; then
          sudo apt-get update
          if ! sudo apt-get install -y linux-headers-$(uname -r) ; then
             cd /lib/modules && sudo ln -sf 4.4.0-97-generic `uname -r` && \
               cd ~/project
          fi
          cd tools/lkl && ./scripts/dpdk-sdk-build.sh;
        fi
  - run:
      name: start emulator
      command: |
        if [[ $CROSS_COMPILE == *android* ]]; then
          emulator -list-avds
          emulator -avd Nexus5_API24 -no-window -no-audio -no-boot-anim;
        elif [[ $CROSS_COMPILE == *freebsd* ]] || [[ -n "$LKL_QEMU_TEST" ]]; then
          cd /home/ubuntu && eval $QEMU
        fi
      background: true
  - run: cd tools/lkl && make -j8 ${MKARG}
  - run: mkdir -p ~/destdir && cd tools/lkl && make DESTDIR=~/destdir && echo 1 >> ~/destdir/dummy && mkdir -p ~/destdir/dummydir 
  - save_cache:
     paths:
       - ~/.ccache
     key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
  - run:
      name: wait emulator to boot
      command: |
        if [[ $CROSS_COMPILE == *android* ]]; then
        cd ~;
        wget -c https://github.com/thehajime/lkl-docker/raw/master/circleci/android/circle-android.sh;
          ~/circle-android.sh wait-for-boot;
          cd -;
        elif [[ $CROSS_COMPILE == *freebsd* ]] || [[ -n "$LKL_QEMU_TEST" ]]; then
          while ! $MYSSH -o ConnectTimeout=1 exit 2> /dev/null
          do
             sleep 5
          done
        fi
  - run:
      name: run tests
      command: |
        mkdir -p ~/junit
        make -C tools/lkl run-tests tests="--junit-dir ~/junit"
        find ./tools/lkl/ -type f -name "*.xml" -exec cp -r  {} ~/junit/ \;
      no_output_timeout: "90m"
  - run: 
      name: package
      command: |
        mkdir -p ~/package
        cd ~/package
        tar -cvf lkl.tar -C  ~/prpject/tools/lkl .
        tar -cvf dest.tar -C  ~/destdir .
        tar -cvf arch.tar -C  ~/project/arch/lkl .
        tar -cvf dest.tar -C  ~/junit .
  - store_test_results:
      path: ~/junit
  - store_artifacts:
      path: ~/package/junit.tar
      destination: junit.tar
  - store_artifacts:
      path: ~/package/lkl.tar
      destination: lkl.tar
  - store_artifacts:
     path: ~/package/dest.tar
     destination: dest.tar
  - store_artifacts:
     path: ~/package/arch.tar
     destination: arch.tar
## Customize the test machine
jobs:
  x86_64:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
     MKARG: "dpdk=no"
     DEBIAN_FRONTEND: noninteractive
   <<: *do_steps

  android-aarch64-new:
    docker:
      - image: javiersantos/android-ci:latest
    environment:
      CROSS_COMPILE: "aarch64-linux-android-"
      LKL_ANDROID_TEST: 1
      DEBIAN_FRONTEND: noninteractive
      PATH: /usr/lib/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sdk/tools:/sdk/build-tools/28.0.3
    <<: *do_steps
    
  android-aarch64:
   docker:
     - image: lkldocker/circleci-android-arm64:0.6
   environment:
     CROSS_COMPILE: "aarch64-linux-android-"
     LKL_ANDROID_TEST: 1
     ANDROID_SDK_ROOT: /home/ubuntu/android-sdk
     DEBIAN_FRONTEND: noninteractive
   <<: *do_steps

  freebsd11_x86_64:
   docker:
     - image: lkldocker/circleci-freebsd11-x86_64:0.4
   environment:
     CROSS_COMPILE: "x86_64-pc-freebsd11-"
     DEBIAN_FRONTEND: noninteractive
   <<: *do_steps

  x86_64_valgrind:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
     MKARG: "dpdk=no"
     DEBIAN_FRONTEND: noninteractive
     VALGRIND: 1
   <<: *do_steps

  x86_64_qemu:
   docker:
     - image: lkldocker/circleci-qemu-x86_64:v1.2
   environment:
     CROSS_COMPILE: ""
     MKARG: "dpdk=no"
     DEBIAN_FRONTEND: noninteractive
     LKL_QEMU_TEST: 1
   <<: *do_steps

workflows:
  version: 2
  build:
    jobs:
     - android-aarch64
